name: kr3j5v0j's blog
title: kr3j5v0j's blog
description: Reverse engeneering blog
tags:
  - blog
  - reverse engeneering
  - binary exploitation
  - cybersecurity
show_hero: true
menu:
  - title: Home
    url: /
  - title: CTF write-ups
    url: /category/CTF write-up/
  - title: Blog
    url: /category/blog/
  - title: About
    url: /about
  - title: Contact
    url: /contact
email: krejsavojtech21@gmail.com

disqus_username: 
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: 

